source 'https://rubygems.org'

gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'sinatra-contrib', '~> 1.4', '>= 1.4.7'
gem 'data_mapper', '~> 1.2'
gem 'dm-sqlite-adapter', '~> 1.2'
gem 'dm-mysql-adapter', '~> 1.2'
gem 'faker', '~> 1.6', '>= 1.6.6'
gem 'thin', '~> 1.7'
gem 'faker', '~> 1.6', '>= 1.6.6'